### ISSUE TITLE
BTTV channel emotes are not visible in the All tab

### ISSUE THREAD

**Issue by neris** [Lordmau5/The-FFZ-Addon-Pack#13]
If the channel has BTTV channel emotes configured, they are visible only on the 'Channel' tab of the emotes menu.
Is it possible to duplicate these emotes on the 'All' tab? Or make it a configurable option?

**Comment by Lordmau5** [comment]
I asked SirStendec about this issue, as I was wondering why they weren't showing up either.

He said that the tabs are as follow:
- `Channel` Tab **=>** Emotes only usable in channel
- `All` Tab **=>** Emotes usable everywhere

So yea.

He additionally considered renaming it back to "My Emotes" due to potential confusion for more users than just us 2 😛
