### ISSUE TITLE
doesn't load/fetch bttv gif emotes in chat-only mode

### ISSUE THREAD

**Issue by rhazor** [Lordmau5/The-FFZ-Addon-Pack#3]
reproduce: go to twitch.com/channel/chat no bttv emotes loaded/available. same with bttv addon.

**Comment by Lordmau5** [comment]
> same with bttv addon

Do you mean that if you use the BTTV extension itself, it doesn't work?

**Comment by rhazor** [comment]
same problem with both addons. both addons dont load e.g. in Tab quick auto fill none of BTTV emotes.

**Comment by Lordmau5** [comment]
If you have BTTV installed, FFZ:AP's BTTV module won't work, which means it's an issue on BTTV's end.

If you don't have BTTV installed / enabled, FFZ:AP's BTTV module should work. If it still doesn't, it might be an issue on their side regardless due to not being able to get the emotes off their website properly.
